/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ScoresStudentManagementClient.View;

import ScoresStudentManagementClient.model.MonHoc;
import bo.Xuly;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.SSLSocket;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quang
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    protected Socket socket = new Socket("127.0.0.1", 9898);
    protected BufferedReader in;
    protected PrintWriter out;
    int AccidTemp = 0;

    public Main(int Quyen) throws IOException, ClassNotFoundException, SQLException {
        initComponents();

        in = new BufferedReader(
                new InputStreamReader(socket.getInputStream()));
        out = new PrintWriter(socket.getOutputStream(), true);

        if (Quyen == 2) {
            btnSua.setVisible(false);
            btnAddAccount.setVisible(false);
            btnXoa.setVisible(false);
            btnAddLophoc.setVisible(false);
            btnAddMonhoc.setVisible(false);
            pnMonHoc.setVisible(false);
            pnLopHoc.setVisible(false);
        }
        loadAccount();
        loadMonhoc();
        loadlophoc();
        setCbLophoc();

    }

    private Main() throws IOException {
        //
    }

    void loadAccount() throws IOException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllTaikhoan();

        Vector cols = new Vector();
        cols.addElement("MãTK");
        cols.addElement("Tên đăng nhập");
        cols.addElement("Tên đầy đủ");
        cols.addElement("Ngày sinh");
        cols.addElement("Giới tính");
        cols.addElement("Lớp học");
        cols.addElement("Quyền");

        Vector data = new Vector();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            u.addElement(ss[0]);
            u.addElement(ss[1]);
            u.addElement(ss[2]);
            u.addElement(ss[3]);
            u.addElement(ss[4].equals("true") ? "Nam" : "Nữ");
            u.addElement(ss[5]);
            u.addElement(ss[6].equals("1") ? "Admin" : ss[6].equals("2") ? "Giảng viên" : "Sinh viên");
            data.add(u);
        }
        jTable1.setModel(new DefaultTableModel(data, cols));

    }

//    public Main(Login login) {
//        super();
//        initComponents();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPhanquyen = new javax.swing.JTabbedPane();
        pnTaiKhoan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTaiKhoan = new javax.swing.JLabel();
        lbHoVaTen = new javax.swing.JLabel();
        lbMatKhau = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtHoVaTen = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        lbTaiKhoan1 = new javax.swing.JLabel();
        lbTaiKhoan2 = new javax.swing.JLabel();
        lbTaiKhoan3 = new javax.swing.JLabel();
        btnAddAccount = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtNgaySinh = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox();
        lbTaiKhoan4 = new javax.swing.JLabel();
        cbQuyen = new javax.swing.JComboBox();
        btnXemdiem = new javax.swing.JButton();
        cbLophoc = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnMonHoc = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMonhoc = new javax.swing.JTable();
        btnAddMonhoc = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMHTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbMHKhoa = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbMHNam = new javax.swing.JComboBox();
        btnXoaMon = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        cbMH_hocki = new javax.swing.JComboBox();
        btnUpdateMonhoc = new javax.swing.JButton();
        pnLopHoc = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLophoc = new javax.swing.JTable();
        btnAddLophoc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTenlop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbKhoa = new javax.swing.JComboBox();
        cbNienkhoa = new javax.swing.JComboBox();
        btnXoalop = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnDiem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDiem = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        cbMonhoc = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbHocki = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        btnSuadiemthi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình quản lý điểm sinh viên");

        pnPhanquyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPhanquyenMouseClicked(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(506, 144));

        lbTaiKhoan.setText("Tài khoản:");

        lbHoVaTen.setText("Họ và tên:");

        lbMatKhau.setText("Mật khẩu:");

        txtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaiKhoanActionPerformed(evt);
            }
        });

        lbTaiKhoan1.setText("Ngày sinh:");

        lbTaiKhoan2.setText("Giới tính:");

        lbTaiKhoan3.setText("Lớp học:");

        btnAddAccount.setText("Thêm mới");
        btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccountActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nữ", "Nam" }));

        lbTaiKhoan4.setText("Quyền:");

        cbQuyen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Giảng viên", "Sinh viên" }));

        btnXemdiem.setText("Xem điểm");
        btnXemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemdiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTaiKhoan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbHoVaTen)
                                    .addComponent(lbMatKhau))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTaiKhoan2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTaiKhoan4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTaiKhoan1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTaiKhoan3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLophoc, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXemdiem)
                        .addGap(163, 163, 163)
                        .addComponent(btnAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTaiKhoan)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan1)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoVaTen)
                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan3)
                    .addComponent(cbLophoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan2)
                    .addComponent(cbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan4))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAccount)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnXemdiem))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnTaiKhoanLayout = new javax.swing.GroupLayout(pnTaiKhoan);
        pnTaiKhoan.setLayout(pnTaiKhoanLayout);
        pnTaiKhoanLayout.setHorizontalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnTaiKhoanLayout.setVerticalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );

        pnPhanquyen.addTab("Tài khoản", pnTaiKhoan);

        pnMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMonHocMouseClicked(evt);
            }
        });

        tbMonhoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMonhoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMonhocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbMonhoc);

        btnAddMonhoc.setText("Thêm môn học");
        btnAddMonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMonhocActionPerformed(evt);
            }
        });

        jLabel7.setText("Tên môn học:");

        jLabel8.setText("Khoa");

        cbMHKhoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Luat", "Quan ly", "Quan tri kinh doanh", "Khoa hoc may tinh", "Kien truc", "Giao duc dao tao" }));

        jLabel9.setText("Năm học");

        cbMHNam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        btnXoaMon.setText("Xóa môn");
        btnXoaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMonActionPerformed(evt);
            }
        });

        jLabel11.setText("Học kì");

        cbMH_hocki.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        btnUpdateMonhoc.setText("Sửa");
        btnUpdateMonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMonhocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMonHocLayout = new javax.swing.GroupLayout(pnMonHoc);
        pnMonHoc.setLayout(pnMonHocLayout);
        pnMonHocLayout.setHorizontalGroup(
            pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnMonHocLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMHTen)
                    .addComponent(cbMHKhoa, 0, 219, Short.MAX_VALUE)
                    .addComponent(cbMHNam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMH_hocki, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddMonhoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateMonhoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaMon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMonHocLayout.setVerticalGroup(
            pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMonhoc)
                    .addComponent(jLabel7)
                    .addComponent(txtMHTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaMon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbMHKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateMonhoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMHNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMH_hocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnPhanquyen.addTab("Môn học", pnMonHoc);

        pnLopHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnLopHocFocusGained(evt);
            }
        });
        pnLopHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLopHocMouseClicked(evt);
            }
        });

        tbLophoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbLophoc);

        btnAddLophoc.setText("Thêm lớp");
        btnAddLophoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLophocActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên lớp");

        jLabel5.setText("Khóa:");

        jLabel6.setText("Khoa:");

        cbKhoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Luat", "Quan ly", "Quan tri kinh doanh", "Khoa hoc may tinh", "Kien truc", "Giao duc dao tao" }));

        cbNienkhoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        btnXoalop.setText("Xóa lớp");
        btnXoalop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoalopActionPerformed(evt);
            }
        });

        jButton1.setText("Sửa");

        javax.swing.GroupLayout pnLopHocLayout = new javax.swing.GroupLayout(pnLopHoc);
        pnLopHoc.setLayout(pnLopHocLayout);
        pnLopHocLayout.setHorizontalGroup(
            pnLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLopHocLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnLopHocLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenlop, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLopHocLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cbKhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnLopHocLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cbNienkhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddLophoc, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnXoalop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnLopHocLayout.setVerticalGroup(
            pnLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenlop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnAddLophoc)
                    .addComponent(btnXoalop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbNienkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnPhanquyen.addTab("Lớp học", pnLopHoc);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Thông tin điểm thi");

        tbDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDiemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbDiem);

        jButton10.setText("Thêm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setText("Môn:");

        jButton12.setText("Xóa");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel3.setText("Điểm");

        cbHocki.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        jLabel10.setText("Học kì");

        btnSuadiemthi.setText("Sửa");
        btnSuadiemthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuadiemthiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbMonhoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbHocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(btnSuadiemthi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(cbMonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton12)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnSuadiemthi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnDiemLayout = new javax.swing.GroupLayout(pnDiem);
        pnDiem.setLayout(pnDiemLayout);
        pnDiemLayout.setHorizontalGroup(
            pnDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDiemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(189, 189, 189))
        );
        pnDiemLayout.setVerticalGroup(
            pnDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnPhanquyen.addTab("Quản lý điểm", pnDiem);

        jMenu1.setText("File");

        jMenuItem1.setText("Log out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("About");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPhanquyen)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPhanquyen, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanActionPerformed

    // add account   
    private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccountActionPerformed
        if (!txtHoVaTen.getText().trim().equals("")) {
            int gioitinh = cbGioiTinh.getSelectedIndex();
            int quyen = cbQuyen.getSelectedIndex() + 1;
            try {
                new Xuly(socket, in, out).AddTaikhoan(txtTaiKhoan.getText(), txtHoVaTen.getText(), txtMatKhau.getText(), txtNgaySinh.getText(), gioitinh, cbLophoc.getSelectedIndex() + 1, quyen);
                JOptionPane optionPane = new JOptionPane("Đã thêm tài khoản", 1);
                JDialog dialog = optionPane.createDialog(this, "Succes");
                dialog.setVisible(true);

            } catch (IOException ex) {
                JOptionPane optionPane = new JOptionPane("Thêm tài khoản không thành công, thử i lại!", 0);
                JDialog dialog = optionPane.createDialog(this, "Lỗi");
                dialog.setVisible(true);
                reconect();
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                loadAccount();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane optionPane = new JOptionPane("Tên tài khoản ko được để trống!", 0);
            JDialog dialog = optionPane.createDialog(this, "Lỗi");
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnAddAccountActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            String id = jTable1.getValueAt(row, 0).toString();
            txtTaiKhoan.setText(jTable1.getValueAt(row, 1).toString());
            txtHoVaTen.setText(jTable1.getValueAt(row, 2).toString());
            txtNgaySinh.setText(jTable1.getValueAt(row, 3).toString());
            cbGioiTinh.setSelectedIndex(jTable1.getValueAt(row, 4).toString().equals("Nam") ? 1 : 0);
            //txtLopHoc.setText(jTable1.getValueAt(row, 5).toString());
            cbLophoc.setSelectedIndex(Integer.parseInt(jTable1.getValueAt(row, 5).toString()) - 1);
            cbQuyen.setSelectedItem(jTable1.getValueAt(row, 6).toString());
            txtMatKhau.setText("");
        }
    }//GEN-LAST:event_jTable1MouseClicked
    void reconect() {
        try {
            socket = new Socket("127.0.0.1", 9898);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //update tai khoan
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        int gioitinh = cbGioiTinh.getSelectedIndex();
        int quyen = cbQuyen.getSelectedIndex() + 1;
        try {
            new Xuly(socket, in, out).UpdateTaikhoan(id, txtTaiKhoan.getText(), txtHoVaTen.getText(), txtNgaySinh.getText(), gioitinh, cbLophoc.getSelectedIndex() + 1, quyen);
            JOptionPane optionPane = new JOptionPane("Đã sửa tài khoản", 1);
            JDialog dialog = optionPane.createDialog(this, "Succes");
            dialog.setVisible(true);
        } catch (IOException ex) {
            JOptionPane optionPane = new JOptionPane("Sửa tài khoản không thành công, thử lại!", 0);
            reconect();
            JDialog dialog = optionPane.createDialog(this, "Lỗi");
            dialog.setVisible(true);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            loadAccount();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    //delete
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog(null, "Xác nhận xóa?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {

        } else if (response == JOptionPane.YES_OPTION) {
            try {
                new Xuly(socket, in, out).DeleteTaiKhoan(id);
                JOptionPane optionPane = new JOptionPane("Đã xóa tài khoản", 1);
                JDialog dialog = optionPane.createDialog(this, "Succes");
                dialog.setVisible(true);
            } catch (IOException ex) {
                JOptionPane optionPane = new JOptionPane("Lỗi kết nối, thử  lại!", 0);
                JDialog dialog = optionPane.createDialog(this, "Lỗi");
                dialog.setVisible(true);
                reconect();
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (response == JOptionPane.CLOSED_OPTION) {

        }
        try {
            loadAccount();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemdiemActionPerformed
        int row = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        if (id < 1) {
            JOptionPane optionPane = new JOptionPane("Select again", 1);
            JDialog dialog = optionPane.createDialog(this, "Error");
            dialog.setVisible(true);
        } else {

            pnPhanquyen.setSelectedIndex(3);
            loadDiem(id);
            AccidTemp = id;
            try {
                setCbMonhoc();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXemdiemActionPerformed

    private void tbDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDiemMouseClicked
        int row = tbDiem.getSelectedRow();
        txtDiem.setText(tbDiem.getValueAt(row, 3).toString());
        cbMonhoc.setSelectedItem(tbDiem.getValueAt(row, 2).toString());
        cbHocki.setSelectedItem(tbDiem.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tbDiemMouseClicked

    private void pnPhanquyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPhanquyenMouseClicked

    }//GEN-LAST:event_pnPhanquyenMouseClicked

    private void pnMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMonHocMouseClicked
        // TODO add your handling code here: 

    }//GEN-LAST:event_pnMonHocMouseClicked

    private void pnLopHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLopHocMouseClicked

    }//GEN-LAST:event_pnLopHocMouseClicked

    private void pnLopHocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnLopHocFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pnLopHocFocusGained

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int row = jTable1.getSelectedRow();
        int Accid = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        int monthiID = cbMonhoc.getSelectedIndex() + 1;
        int diem = Integer.parseInt(txtDiem.getText());
        int hocki = cbHocki.getSelectedIndex() + 1;
        try {
            new Xuly(socket, in, out).AddDiemThi(Accid, monthiID, diem, hocki);
            loadDiem(Accid);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    //DELETE diem thi
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int row = tbDiem.getSelectedRow();
        int id = Integer.parseInt(tbDiem.getValueAt(row, 0).toString());
        int rowtk = jTable1.getSelectedRow();
        int idtk = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog(null, "Xác nhận xóa?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {

        } else if (response == JOptionPane.YES_OPTION) {
            try {
                new Xuly(socket, in, out).DeleteDiemThi(id);

            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane optionPane = new JOptionPane("Đã xóa ", 1);
            JDialog dialog = optionPane.createDialog(this, "Succes");
            dialog.setVisible(true);
        }
        loadDiem(AccidTemp);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnAddLophocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLophocActionPerformed
        try {
            new Xuly(socket, in, out).AddLophoc(txtTenlop.getText(), cbKhoa.getSelectedItem().toString(), cbNienkhoa.getSelectedItem().toString());
            loadlophoc();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddLophocActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Login lg;

        try {
            lg = new Login();
            lg.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnAddMonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMonhocActionPerformed
        try {
            new Xuly(socket, in, out).AddMonhoc(txtMHTen.getText(), cbMHKhoa.getSelectedItem().toString(), cbMHNam.getSelectedItem().toString(), cbMH_hocki.getSelectedItem().toString());
            loadMonhoc();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddMonhocActionPerformed

    //delete lop hoc
    private void btnXoalopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoalopActionPerformed
        int row = tbLophoc.getSelectedRow();
        int id = Integer.parseInt(tbLophoc.getValueAt(row, 0).toString());
        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog(null, "Xác nhận xóa?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {

        } else if (response == JOptionPane.YES_OPTION) {
            try {
                new Xuly(socket, in, out).Deletelophoc(id);
                loadlophoc();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXoalopActionPerformed

    // delete mon hoc
    private void btnXoaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMonActionPerformed
        int row = tbMonhoc.getSelectedRow();
        int id = Integer.parseInt(tbMonhoc.getValueAt(row, 0).toString());
        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog(null, "Xác nhận xóa?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {

        } else if (response == JOptionPane.YES_OPTION) {
            try {
                new Xuly(socket, in, out).DeleteMonhoc(id);
                loadMonhoc();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXoaMonActionPerformed

    // mouse click mon hoc
    private void tbMonhocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMonhocMouseClicked
        int row = tbMonhoc.getSelectedRow();
        txtMHTen.setText(tbMonhoc.getValueAt(row, 1).toString());
        cbMHKhoa.setSelectedItem(tbMonhoc.getValueAt(row, 2).toString());
        cbMHNam.setSelectedItem(tbMonhoc.getValueAt(row, 3).toString());
        cbMHNam.setSelectedItem(tbMonhoc.getValueAt(row, 3).toString());
        cbMH_hocki.setSelectedItem(tbMonhoc.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tbMonhocMouseClicked

    //update diem thi
    private void btnSuadiemthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuadiemthiActionPerformed
        int row = tbDiem.getSelectedRow();
        int id = Integer.parseInt(tbDiem.getValueAt(row, 0).toString());
        try {
            new Xuly(socket, in, out).UpdateDiemthi(id, cbMonhoc.getSelectedIndex() + 1, Integer.parseInt(txtDiem.getText()), cbHocki.getSelectedIndex() + 1);
            JOptionPane optionPane = new JOptionPane("Đã sửa điểm", 1);
            JDialog dialog = optionPane.createDialog(this, "Succes");
            dialog.setVisible(true);
            loadDiem(AccidTemp);
        } catch (IOException ex) {
            JOptionPane optionPane = new JOptionPane("Sửa điểm thi không thành công, thử lại!", 0);
            reconect();
            JDialog dialog = optionPane.createDialog(this, "Lỗi");
            dialog.setVisible(true);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSuadiemthiActionPerformed

    //update mon hoc
    private void btnUpdateMonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMonhocActionPerformed
        int row = tbMonhoc.getSelectedRow();
        int id = Integer.parseInt(tbMonhoc.getValueAt(row, 0).toString());
        try {
            new Xuly(socket, in, out).UpdateMonhoc(id, txtMHTen.getText(), cbMHKhoa.getSelectedItem().toString(), cbMHNam.getSelectedItem().toString(), Integer.parseInt((String) cbMH_hocki.getSelectedItem()));
            JOptionPane optionPane = new JOptionPane("Đã update môn học", 1);
            JDialog dialog = optionPane.createDialog(this, "Succes");
            dialog.setVisible(true);
            loadMonhoc();
        } catch (IOException ex) {
            JOptionPane optionPane = new JOptionPane("Sửa điểm thi không thành công, thử lại!", 0);
            reconect();
            JDialog dialog = optionPane.createDialog(this, "Lỗi");
            dialog.setVisible(true);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateMonhocActionPerformed

    void loadDiem(int Accountid) {
        Vector data = new Vector();
        try {
            ArrayList<String> a = new Xuly(socket, in, out).GetAllDiemthi(Accountid);
            for (String s : a) {
                Vector u = new Vector();
                String[] ss = s.split(";");
                u.addElement(ss[0]);
                u.addElement(ss[1]);
                u.addElement(ss[2]);
                u.addElement(ss[3]);
                u.addElement(ss[4]);
                data.add(u);
            }
        } catch (Exception ee) {
        }
        Vector cols = new Vector();
        cols.addElement("ID");
        cols.addElement("Tên đầy đủ");
        cols.addElement("Môn học");
        cols.addElement("Điểm");
        cols.addElement("Học kì");
        tbDiem.setModel(new DefaultTableModel(data, cols));
    }

    void setCbMonhoc() throws IOException, SQLException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllMonhoc();
        cbMonhoc.removeAllItems();
        ArrayList<MonHoc> list = new ArrayList<>();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            cbMonhoc.addItem(ss[1]);
        }
    }

    void setCbLophoc() throws IOException, SQLException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllLophoc();
        cbLophoc.removeAllItems();
        ArrayList<MonHoc> list = new ArrayList<>();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            cbLophoc.addItem(ss[1]);
        }
    }

    ArrayList<MonHoc> getListMonhoc() throws IOException, SQLException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllMonhoc();
        ArrayList<MonHoc> list = new ArrayList<>();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            list.add(new MonHoc(Integer.parseInt(ss[0]), ss[1]));
        }
        return list;
    }

    ArrayList<MonHoc> getListLophoc() throws IOException, SQLException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllLophoc();
        ArrayList<MonHoc> list = new ArrayList<>();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            list.add(new MonHoc(Integer.parseInt(ss[0]), ss[1]));
        }
        return list;
    }

    void loadMonhoc() {
        Vector data = new Vector();
        try {
            ArrayList<String> a = new Xuly(socket, in, out).GetAllMonhoc();
            for (String s : a) {
                Vector u = new Vector();
                String[] ss = s.split(";");
                u.addElement(ss[0]);
                u.addElement(ss[1]);
                u.addElement(ss[2]);
                u.addElement(ss[3]);
                u.addElement(ss[4]);
                data.add(u);
            }
        } catch (Exception ee) {
        }
        Vector cols = new Vector();
        cols.addElement("Mã môn");
        cols.addElement("Môn học");
        cols.addElement("Khoa");
        cols.addElement("Nam hoc");
        cols.addElement("Hoc ki");
        tbMonhoc.setModel(new DefaultTableModel(data, cols));
    }

    void loadlophoc() {
        Vector data = new Vector();
        try {
            ArrayList<String> a = new Xuly(socket, in, out).GetAllLophoc();
            for (String s : a) {
                Vector u = new Vector();
                String[] ss = s.split(";");
                u.addElement(ss[0]);
                u.addElement(ss[1]);
                u.addElement(ss[2]);
                u.addElement(ss[3]);
                data.add(u);
            }
        } catch (Exception ee) {
        }
        Vector cols = new Vector();
        cols.addElement("Mã lớp");
        cols.addElement("Lớp học");
        cols.addElement("Khoa");
        cols.addElement("Niên khóa");
        tbLophoc.setModel(new DefaultTableModel(data, cols));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnAddLophoc;
    private javax.swing.JButton btnAddMonhoc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuadiemthi;
    private javax.swing.JButton btnUpdateMonhoc;
    private javax.swing.JButton btnXemdiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JToggleButton btnXoaMon;
    private javax.swing.JButton btnXoalop;
    private javax.swing.JComboBox cbGioiTinh;
    private javax.swing.JComboBox cbHocki;
    private javax.swing.JComboBox cbKhoa;
    private javax.swing.JComboBox cbLophoc;
    private javax.swing.JComboBox cbMHKhoa;
    private javax.swing.JComboBox cbMHNam;
    private javax.swing.JComboBox cbMH_hocki;
    private javax.swing.JComboBox cbMonhoc;
    private javax.swing.JComboBox cbNienkhoa;
    private javax.swing.JComboBox cbQuyen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbHoVaTen;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JLabel lbTaiKhoan1;
    private javax.swing.JLabel lbTaiKhoan2;
    private javax.swing.JLabel lbTaiKhoan3;
    private javax.swing.JLabel lbTaiKhoan4;
    private javax.swing.JPanel pnDiem;
    private javax.swing.JPanel pnLopHoc;
    private javax.swing.JPanel pnMonHoc;
    private javax.swing.JTabbedPane pnPhanquyen;
    private javax.swing.JPanel pnTaiKhoan;
    private javax.swing.JTable tbDiem;
    private javax.swing.JTable tbLophoc;
    private javax.swing.JTable tbMonhoc;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtMHTen;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTenlop;
    // End of variables declaration//GEN-END:variables
}
