/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ScoresStudentManagementClient.View;

import ScoresStudentManagementClient.model.MonHoc;
import bo.Xuly;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.SSLSocket;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quang
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    protected Socket socket = new Socket("127.0.0.1", 9898);
    protected BufferedReader in;
    protected PrintWriter out;
    int AccidTemp = 0;
    public Main() throws IOException, ClassNotFoundException, SQLException {
        initComponents();

        in = new BufferedReader(
                new InputStreamReader(socket.getInputStream()));
        out = new PrintWriter(socket.getOutputStream(), true);

        loadAccount();
        loadMonhoc();
        loadlophoc();
        setCbLophoc() ;
    }

    void loadAccount() throws IOException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllTaikhoan();

        Vector cols = new Vector();
        cols.addElement("ID");
        cols.addElement("Tên đăng nhập");
        cols.addElement("Tên đầy đủ");
        cols.addElement("Ngày sinh");
        cols.addElement("Giới tính");
        cols.addElement("Lớp học");
        cols.addElement("Quyền");

        Vector data = new Vector();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            u.addElement(ss[0]);
            u.addElement(ss[1]);
            u.addElement(ss[2]);
            u.addElement(ss[3]);
            u.addElement(ss[4].equals("true") ? "Nam" : "Nữ");
            u.addElement(ss[5]);
            u.addElement(ss[6].equals("1") ? "Admin" : ss[6].equals("2") ? "Giảng viên" : "Sinh viên");
            data.add(u);
        }
        jTable1.setModel(new DefaultTableModel(data, cols));

    }

//    public Main(Login login) {
//        super();
//        initComponents();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnTaiKhoan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTaiKhoan = new javax.swing.JLabel();
        lbHoVaTen = new javax.swing.JLabel();
        lbMatKhau = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtHoVaTen = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        lbTaiKhoan1 = new javax.swing.JLabel();
        lbTaiKhoan2 = new javax.swing.JLabel();
        lbTaiKhoan3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtNgaySinh = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox();
        lbTaiKhoan4 = new javax.swing.JLabel();
        cbQuyen = new javax.swing.JComboBox();
        btnXemdiem = new javax.swing.JButton();
        cbLophoc = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnMonHoc = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMonhoc = new javax.swing.JTable();
        pnLopHoc = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLophoc = new javax.swing.JTable();
        pnDiem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDiem = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        cbMonhoc = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình quản lý điểm sinh viên");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(506, 144));

        lbTaiKhoan.setText("Tài khoản:");

        lbHoVaTen.setText("Họ và tên:");

        lbMatKhau.setText("Mật khẩu:");

        txtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaiKhoanActionPerformed(evt);
            }
        });

        lbTaiKhoan1.setText("Ngày sinh:");

        lbTaiKhoan2.setText("Giới tính:");

        lbTaiKhoan3.setText("Lớp học:");

        jButton1.setText("Thêm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nữ", "Nam" }));

        lbTaiKhoan4.setText("Quyền:");

        cbQuyen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Giảng viên", "Sinh viên" }));

        btnXemdiem.setText("Xem điểm");
        btnXemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemdiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTaiKhoan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbHoVaTen)
                                    .addComponent(lbMatKhau))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTaiKhoan2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTaiKhoan4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTaiKhoan1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTaiKhoan3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLophoc, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXemdiem)
                        .addGap(163, 163, 163)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTaiKhoan)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan1)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoVaTen)
                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan3)
                    .addComponent(cbLophoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan2)
                    .addComponent(cbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan4))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btnXemdiem))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnTaiKhoanLayout = new javax.swing.GroupLayout(pnTaiKhoan);
        pnTaiKhoan.setLayout(pnTaiKhoanLayout);
        pnTaiKhoanLayout.setHorizontalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnTaiKhoanLayout.setVerticalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tài khoản", pnTaiKhoan);

        pnMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMonHocMouseClicked(evt);
            }
        });

        tbMonhoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbMonhoc);

        javax.swing.GroupLayout pnMonHocLayout = new javax.swing.GroupLayout(pnMonHoc);
        pnMonHoc.setLayout(pnMonHocLayout);
        pnMonHocLayout.setHorizontalGroup(
            pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnMonHocLayout.setVerticalGroup(
            pnMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMonHocLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Môn học", pnMonHoc);

        pnLopHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnLopHocFocusGained(evt);
            }
        });
        pnLopHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLopHocMouseClicked(evt);
            }
        });

        tbLophoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbLophoc);

        javax.swing.GroupLayout pnLopHocLayout = new javax.swing.GroupLayout(pnLopHoc);
        pnLopHoc.setLayout(pnLopHocLayout);
        pnLopHocLayout.setHorizontalGroup(
            pnLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLopHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnLopHocLayout.setVerticalGroup(
            pnLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLopHocLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lớp học", pnLopHoc);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Thông tin điểm thi");

        tbDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDiemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbDiem);

        jButton10.setText("Thêm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setText("Môn:");

        jButton12.setText("Xóa");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel3.setText("Điểm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbMonhoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(cbMonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton12)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnDiemLayout = new javax.swing.GroupLayout(pnDiem);
        pnDiem.setLayout(pnDiemLayout);
        pnDiemLayout.setHorizontalGroup(
            pnDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDiemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(189, 189, 189))
        );
        pnDiemLayout.setVerticalGroup(
            pnDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Xem điểm", pnDiem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanActionPerformed

    // add account   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int gioitinh = cbGioiTinh.getSelectedIndex();
        int quyen = cbQuyen.getSelectedIndex() + 1;
        try {
            new Xuly(socket, in, out).AddTaikhoan(txtTaiKhoan.getText(), txtHoVaTen.getText(), txtMatKhau.getText(), txtNgaySinh.getText(), gioitinh, cbLophoc.getSelectedIndex()+1, quyen);
            JOptionPane optionPane = new JOptionPane("Đã thêm tài khoản", 1);
            JDialog dialog = optionPane.createDialog(this, "Succes");
            dialog.setVisible(true);

        } catch (IOException ex) {
            JOptionPane optionPane = new JOptionPane("Thêm tài khoản không thành công, thử i lại!", 0);
            JDialog dialog = optionPane.createDialog(this, "Lỗi");
            dialog.setVisible(true);
            reconect();
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            loadAccount();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            String id = jTable1.getValueAt(row, 0).toString();
            txtTaiKhoan.setText(jTable1.getValueAt(row, 1).toString());
            txtHoVaTen.setText(jTable1.getValueAt(row, 2).toString());
            txtNgaySinh.setText(jTable1.getValueAt(row, 3).toString());
            cbGioiTinh.setSelectedIndex(jTable1.getValueAt(row, 4).toString().equals("Nam") ? 1 : 0);
            //txtLopHoc.setText(jTable1.getValueAt(row, 5).toString());
            cbLophoc.setSelectedIndex(Integer.parseInt(jTable1.getValueAt(row, 5).toString())-1);
            cbQuyen.setSelectedItem(jTable1.getValueAt(row, 6).toString());
            txtMatKhau.setText("");
        }
    }//GEN-LAST:event_jTable1MouseClicked
    void reconect() {
        try {
            socket = new Socket("127.0.0.1", 9898);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //update tai khoan
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        int gioitinh = cbGioiTinh.getSelectedIndex();
        int quyen = cbQuyen.getSelectedIndex() + 1;
        try {
            new Xuly(socket, in, out).UpdateTaikhoan(id, txtTaiKhoan.getText(), txtHoVaTen.getText(), txtNgaySinh.getText(), gioitinh,cbLophoc.getSelectedIndex()+1, quyen);
            JOptionPane optionPane = new JOptionPane("Đã sửa tài khoản", 1);
            JDialog dialog = optionPane.createDialog(this, "Succes");
            dialog.setVisible(true);
        } catch (IOException ex) {
            JOptionPane optionPane = new JOptionPane("Sửa tài khoản không thành công, thử lại!", 0);
            reconect();
            JDialog dialog = optionPane.createDialog(this, "Lỗi");
            dialog.setVisible(true);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            loadAccount();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    //delete
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog(null, "Xác nhận xóa?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {

        } else if (response == JOptionPane.YES_OPTION) {
            try {
                new Xuly(socket, in, out).DeleteTaiKhoan(id);
                JOptionPane optionPane = new JOptionPane("Đã xóa tài khoản", 1);
                JDialog dialog = optionPane.createDialog(this, "Succes");
                dialog.setVisible(true);
            } catch (IOException ex) {
                JOptionPane optionPane = new JOptionPane("Lỗi kết nối, thử  lại!", 0);
                JDialog dialog = optionPane.createDialog(this, "Lỗi");
                dialog.setVisible(true);
                reconect();
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (response == JOptionPane.CLOSED_OPTION) {

        }
        try {
            loadAccount();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnXemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemdiemActionPerformed
        int row = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        if (id < 1) {
            JOptionPane optionPane = new JOptionPane("Select again", 1);
            JDialog dialog = optionPane.createDialog(this, "Error");
            dialog.setVisible(true);
        } else {

            jTabbedPane1.setSelectedIndex(3);
            loadDiem(id);
            AccidTemp = id;
            try {
                setCbMonhoc();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXemdiemActionPerformed

    private void tbDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDiemMouseClicked
        int row = tbDiem.getSelectedRow();
        txtDiem.setText(tbDiem.getValueAt(row, 3).toString());
        cbMonhoc.setSelectedItem(tbDiem.getValueAt(row, 2).toString());

    }//GEN-LAST:event_tbDiemMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void pnMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMonHocMouseClicked
        // TODO add your handling code here: 

    }//GEN-LAST:event_pnMonHocMouseClicked

    private void pnLopHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLopHocMouseClicked

    }//GEN-LAST:event_pnLopHocMouseClicked

    private void pnLopHocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnLopHocFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pnLopHocFocusGained

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int row = jTable1.getSelectedRow();
        int Accid = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        int monthiID = cbMonhoc.getSelectedIndex()+1;
        int diem = Integer.parseInt(txtDiem.getText());
        try {
            new Xuly(socket, in, out).AddDiemThi(Accid, monthiID, diem);
            loadDiem(Accid);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    //DELETE diem thi
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int row = tbDiem.getSelectedRow();
        int id = Integer.parseInt(tbDiem.getValueAt(row, 0).toString());
            int rowtk = jTable1.getSelectedRow();
        int idtk = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
          JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog(null, "Xác nhận xóa?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {

        } else if (response == JOptionPane.YES_OPTION) {            
            try {
                new Xuly(socket, in, out).DeleteDiemThi(id);
              
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
                JOptionPane optionPane = new JOptionPane("Đã xóa ", 1);
                JDialog dialog = optionPane.createDialog(this, "Succes");
                dialog.setVisible(true);
        }
          loadDiem(AccidTemp);
    }//GEN-LAST:event_jButton12ActionPerformed

    void loadDiem(int Accountid) {
        Vector data = new Vector();
        try {
            ArrayList<String> a = new Xuly(socket, in, out).GetAllDiemthi(Accountid);
            for (String s : a) {
                Vector u = new Vector();
                String[] ss = s.split(";");
                u.addElement(ss[0]);
                u.addElement(ss[1]);
                u.addElement(ss[2]);
                u.addElement(ss[3]);
                data.add(u);
            }
        } catch (Exception ee) {
        }
        Vector cols = new Vector();
        cols.addElement("ID");
        cols.addElement("Tên đầy đủ");
        cols.addElement("Môn học");
        cols.addElement("Điểm");
        tbDiem.setModel(new DefaultTableModel(data, cols));
    }

    void setCbMonhoc() throws IOException, SQLException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllMonhoc();
        cbMonhoc.removeAllItems();
        ArrayList<MonHoc> list = new ArrayList<>();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            cbMonhoc.addItem(ss[1]);
        }
    }

    void setCbLophoc() throws IOException, SQLException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllLophoc();
        cbLophoc.removeAllItems();
        ArrayList<MonHoc> list = new ArrayList<>();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            cbLophoc.addItem(ss[1]);
        }
    }

    ArrayList<MonHoc> getListMonhoc() throws IOException, SQLException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllMonhoc();
        ArrayList<MonHoc> list = new ArrayList<>();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            list.add(new MonHoc(Integer.parseInt(ss[0]), ss[1]));
        }
        return list;
    }

    ArrayList<MonHoc> getListLophoc() throws IOException, SQLException {
        ArrayList<String> a = new Xuly(socket, in, out).GetAllLophoc();
        ArrayList<MonHoc> list = new ArrayList<>();
        for (String s : a) {
            Vector u = new Vector();
            String[] ss = s.split(";");
            list.add(new MonHoc(Integer.parseInt(ss[0]), ss[1]));
        }
        return list;
    }

    void loadMonhoc() {
        Vector data = new Vector();
        try {
            ArrayList<String> a = new Xuly(socket, in, out).GetAllMonhoc();
            for (String s : a) {
                Vector u = new Vector();
                String[] ss = s.split(";");
                u.addElement(ss[0]);
                u.addElement(ss[1]);
                data.add(u);
            }
        } catch (Exception ee) {
        }
        Vector cols = new Vector();
        cols.addElement("ID");
        cols.addElement("Môn học");
        tbMonhoc.setModel(new DefaultTableModel(data, cols));
    }

    void loadlophoc() {
        Vector data = new Vector();
        try {
            ArrayList<String> a = new Xuly(socket, in, out).GetAllLophoc();
            for (String s : a) {
                Vector u = new Vector();
                String[] ss = s.split(";");
                u.addElement(ss[0]);
                u.addElement(ss[1]);
                data.add(u);
            }
        } catch (Exception ee) {
        }
        Vector cols = new Vector();
        cols.addElement("ID");
        cols.addElement("Lớp học");
        tbLophoc.setModel(new DefaultTableModel(data, cols));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXemdiem;
    private javax.swing.JComboBox cbGioiTinh;
    private javax.swing.JComboBox cbLophoc;
    private javax.swing.JComboBox cbMonhoc;
    private javax.swing.JComboBox cbQuyen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbHoVaTen;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JLabel lbTaiKhoan1;
    private javax.swing.JLabel lbTaiKhoan2;
    private javax.swing.JLabel lbTaiKhoan3;
    private javax.swing.JLabel lbTaiKhoan4;
    private javax.swing.JPanel pnDiem;
    private javax.swing.JPanel pnLopHoc;
    private javax.swing.JPanel pnMonHoc;
    private javax.swing.JPanel pnTaiKhoan;
    private javax.swing.JTable tbDiem;
    private javax.swing.JTable tbLophoc;
    private javax.swing.JTable tbMonhoc;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
